pipeline {
    agent any
    stages {
        stage("checkout:git") {
            steps {
                git branch: "master", url: "https://github.com/jenkins-docs/simple-java-maven-app"
            }
        }

 

        stage("Build:Maven") {     
            steps {
                sh '$MVN -B -DskipTests clean package' 
            }
        }
        stage("Analise:Sonar") {
            steps {
                sh '$MVN sonar:sonar \
                -Dsonar.projectKey=becaDevOps:master \
                -Dsonar.host.url=http://35.223.7.27:9000 \
                -Dsonar.login=a609b2f86872d0242236a18a024143a56e42a770'
            }
        }
    }
}
